import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'ui_capture_support.dart';

const bool _capturePngs = bool.fromEnvironment('CAPTURE_PNGS');

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  for (final scenario in _captureScenarios) {
    final captureScenario = scenario;
    testWidgets('captures ${captureScenario.name}', (
      WidgetTester tester,
    ) async {
      await captureScenario.capture(tester);
    }, skip: !_capturePngs);
  }
}

final List<UiCaptureScenario> _captureScenarios = <UiCaptureScenario>[
  UiCaptureScenario(
    name: 'windows-login-standard',
    platform: TargetPlatform.windows,
    size: const Size(1440, 960),
    outputPath: '../pngs/windows-login-standard.png',
    variant: UiCaptureVariant.standard,
    action: captureLoginScreen,
  ),
  UiCaptureScenario(
    name: 'windows-login-enhanced',
    platform: TargetPlatform.windows,
    size: const Size(1440, 960),
    outputPath: '../pngs/windows-login-enhanced.png',
    variant: UiCaptureVariant.enhanced,
    action: captureLoginScreen,
  ),
  UiCaptureScenario(
    name: 'windows-chat-standard',
    platform: TargetPlatform.windows,
    size: const Size(1440, 960),
    outputPath: '../pngs/windows-chat-standard.png',
    variant: UiCaptureVariant.standard,
    action: captureDesktopChatShell,
  ),
  UiCaptureScenario(
    name: 'windows-chat-enhanced',
    platform: TargetPlatform.windows,
    size: const Size(1440, 960),
    outputPath: '../pngs/windows-chat-enhanced.png',
    variant: UiCaptureVariant.enhanced,
    action: captureDesktopChatShell,
  ),
  UiCaptureScenario(
    name: 'windows-chat-panel-closed-standard',
    platform: TargetPlatform.windows,
    size: const Size(1440, 960),
    outputPath: '../pngs/windows-chat-panel-closed-standard.png',
    variant: UiCaptureVariant.standard,
    action: captureDesktopChatShellClosed,
  ),
  UiCaptureScenario(
    name: 'windows-chat-panel-closed-enhanced',
    platform: TargetPlatform.windows,
    size: const Size(1440, 960),
    outputPath: '../pngs/windows-chat-panel-closed-enhanced.png',
    variant: UiCaptureVariant.enhanced,
    action: captureDesktopChatShellClosed,
  ),
  UiCaptureScenario(
    name: 'windows-chat-panel-open-standard',
    platform: TargetPlatform.windows,
    size: const Size(1440, 960),
    outputPath: '../pngs/windows-chat-panel-open-standard.png',
    variant: UiCaptureVariant.standard,
    action: captureDesktopChatPanelOpen,
  ),
  UiCaptureScenario(
    name: 'windows-chat-panel-open-enhanced',
    platform: TargetPlatform.windows,
    size: const Size(1440, 960),
    outputPath: '../pngs/windows-chat-panel-open-enhanced.png',
    variant: UiCaptureVariant.enhanced,
    action: captureDesktopChatPanelOpen,
  ),
  UiCaptureScenario(
    name: 'windows-chat-empty-standard',
    platform: TargetPlatform.windows,
    size: const Size(1440, 960),
    outputPath: '../pngs/windows-chat-empty-standard.png',
    variant: UiCaptureVariant.standard,
    sdkClient: EmptyCaptureSdkClient(),
    action: captureDesktopEmptyState,
  ),
  UiCaptureScenario(
    name: 'windows-chat-empty-enhanced',
    platform: TargetPlatform.windows,
    size: const Size(1440, 960),
    outputPath: '../pngs/windows-chat-empty-enhanced.png',
    variant: UiCaptureVariant.enhanced,
    sdkClient: EmptyCaptureSdkClient(),
    action: captureDesktopEmptyState,
  ),
  UiCaptureScenario(
    name: 'windows-shell-standard',
    platform: TargetPlatform.windows,
    size: const Size(1440, 960),
    outputPath: '../pngs/windows-shell.png',
    variant: UiCaptureVariant.standard,
    action: captureDesktopChatShell,
  ),
  UiCaptureScenario(
    name: 'windows-shell-enhanced',
    platform: TargetPlatform.windows,
    size: const Size(1440, 960),
    outputPath: '../pngs/windows-shell-enhanced.png',
    variant: UiCaptureVariant.enhanced,
    action: captureDesktopChatShell,
  ),
  UiCaptureScenario(
    name: 'android-login-standard',
    platform: TargetPlatform.android,
    size: const Size(412, 915),
    outputPath: '../pngs/android-login-standard.png',
    variant: UiCaptureVariant.standard,
    action: captureLoginScreen,
  ),
  UiCaptureScenario(
    name: 'android-login-enhanced',
    platform: TargetPlatform.android,
    size: const Size(412, 915),
    outputPath: '../pngs/android-login-enhanced.png',
    variant: UiCaptureVariant.enhanced,
    action: captureLoginScreen,
  ),
  UiCaptureScenario(
    name: 'android-chat-list-standard',
    platform: TargetPlatform.android,
    size: const Size(412, 915),
    outputPath: '../pngs/android-chat-list-standard.png',
    variant: UiCaptureVariant.standard,
    action: captureMobileChatList,
  ),
  UiCaptureScenario(
    name: 'android-chat-list-enhanced',
    platform: TargetPlatform.android,
    size: const Size(412, 915),
    outputPath: '../pngs/android-chat-list-enhanced.png',
    variant: UiCaptureVariant.enhanced,
    action: captureMobileChatList,
  ),
  UiCaptureScenario(
    name: 'android-chat-detail-standard',
    platform: TargetPlatform.android,
    size: const Size(412, 915),
    outputPath: '../pngs/android-chat-detail-standard.png',
    variant: UiCaptureVariant.standard,
    action: captureMobileChatDetail,
  ),
  UiCaptureScenario(
    name: 'android-chat-detail-enhanced',
    platform: TargetPlatform.android,
    size: const Size(412, 915),
    outputPath: '../pngs/android-chat-detail-enhanced.png',
    variant: UiCaptureVariant.enhanced,
    action: captureMobileChatDetail,
  ),
  UiCaptureScenario(
    name: 'android-contacts-standard',
    platform: TargetPlatform.android,
    size: const Size(412, 915),
    outputPath: '../pngs/android-contacts-standard.png',
    variant: UiCaptureVariant.standard,
    action: captureMobileContacts,
  ),
  UiCaptureScenario(
    name: 'android-contacts-enhanced',
    platform: TargetPlatform.android,
    size: const Size(412, 915),
    outputPath: '../pngs/android-contacts-enhanced.png',
    variant: UiCaptureVariant.enhanced,
    action: captureMobileContacts,
  ),
  UiCaptureScenario(
    name: 'android-settings-security-standard',
    platform: TargetPlatform.android,
    size: const Size(412, 915),
    outputPath: '../pngs/android-settings-security-standard.png',
    variant: UiCaptureVariant.standard,
    action: captureMobileSettingsSecurity,
  ),
  UiCaptureScenario(
    name: 'android-settings-security-enhanced',
    platform: TargetPlatform.android,
    size: const Size(412, 915),
    outputPath: '../pngs/android-settings-security-enhanced.png',
    variant: UiCaptureVariant.enhanced,
    action: captureMobileSettingsSecurity,
  ),
  UiCaptureScenario(
    name: 'android-shell-standard',
    platform: TargetPlatform.android,
    size: const Size(412, 915),
    outputPath: '../pngs/android-shell.png',
    variant: UiCaptureVariant.standard,
    action: captureMobileChatList,
  ),
  UiCaptureScenario(
    name: 'android-shell-enhanced',
    platform: TargetPlatform.android,
    size: const Size(412, 915),
    outputPath: '../pngs/android-shell-enhanced.png',
    variant: UiCaptureVariant.enhanced,
    action: captureMobileChatList,
  ),
  UiCaptureScenario(
    name: 'ios-login-standard',
    platform: TargetPlatform.iOS,
    size: const Size(393, 852),
    outputPath: '../pngs/ios-login-standard.png',
    variant: UiCaptureVariant.standard,
    action: captureLoginScreen,
  ),
  UiCaptureScenario(
    name: 'ios-login-enhanced',
    platform: TargetPlatform.iOS,
    size: const Size(393, 852),
    outputPath: '../pngs/ios-login-enhanced.png',
    variant: UiCaptureVariant.enhanced,
    action: captureLoginScreen,
  ),
  UiCaptureScenario(
    name: 'ios-chat-list-standard',
    platform: TargetPlatform.iOS,
    size: const Size(393, 852),
    outputPath: '../pngs/ios-chat-list-standard.png',
    variant: UiCaptureVariant.standard,
    action: captureMobileChatList,
  ),
  UiCaptureScenario(
    name: 'ios-chat-list-enhanced',
    platform: TargetPlatform.iOS,
    size: const Size(393, 852),
    outputPath: '../pngs/ios-chat-list-enhanced.png',
    variant: UiCaptureVariant.enhanced,
    action: captureMobileChatList,
  ),
  UiCaptureScenario(
    name: 'ios-chat-detail-standard',
    platform: TargetPlatform.iOS,
    size: const Size(393, 852),
    outputPath: '../pngs/ios-chat-detail-standard.png',
    variant: UiCaptureVariant.standard,
    action: captureMobileChatDetail,
  ),
  UiCaptureScenario(
    name: 'ios-chat-detail-enhanced',
    platform: TargetPlatform.iOS,
    size: const Size(393, 852),
    outputPath: '../pngs/ios-chat-detail-enhanced.png',
    variant: UiCaptureVariant.enhanced,
    action: captureMobileChatDetail,
  ),
  UiCaptureScenario(
    name: 'ios-contacts-standard',
    platform: TargetPlatform.iOS,
    size: const Size(393, 852),
    outputPath: '../pngs/ios-contacts-standard.png',
    variant: UiCaptureVariant.standard,
    action: captureMobileContacts,
  ),
  UiCaptureScenario(
    name: 'ios-contacts-enhanced',
    platform: TargetPlatform.iOS,
    size: const Size(393, 852),
    outputPath: '../pngs/ios-contacts-enhanced.png',
    variant: UiCaptureVariant.enhanced,
    action: captureMobileContacts,
  ),
  UiCaptureScenario(
    name: 'ios-settings-security-standard',
    platform: TargetPlatform.iOS,
    size: const Size(393, 852),
    outputPath: '../pngs/ios-settings-security-standard.png',
    variant: UiCaptureVariant.standard,
    action: captureMobileSettingsSecurity,
  ),
  UiCaptureScenario(
    name: 'ios-settings-security-enhanced',
    platform: TargetPlatform.iOS,
    size: const Size(393, 852),
    outputPath: '../pngs/ios-settings-security-enhanced.png',
    variant: UiCaptureVariant.enhanced,
    action: captureMobileSettingsSecurity,
  ),
  UiCaptureScenario(
    name: 'ios-shell-standard',
    platform: TargetPlatform.iOS,
    size: const Size(393, 852),
    outputPath: '../pngs/ios-shell.png',
    variant: UiCaptureVariant.standard,
    action: captureMobileChatList,
  ),
  UiCaptureScenario(
    name: 'ios-shell-enhanced',
    platform: TargetPlatform.iOS,
    size: const Size(393, 852),
    outputPath: '../pngs/ios-shell-enhanced.png',
    variant: UiCaptureVariant.enhanced,
    action: captureMobileChatList,
  ),
];
